rest:
  auth-open: false #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-url: /user/register,/user/check #忽略列表

server:
  port: 8081 #项目端口

mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  application:
    name: film-user
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns_rest?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.com.stylefeng: debug