server:
  port: 8084 #项目端口

mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

spring:
  application:
    name: film-film
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20881
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns_rest?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.com.stylefeng: debug