package com.wwn.film.user.dao;

import com.wwn.film.user.entity.UserPO;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int insert(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int insertSelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    UserPO selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int updateByPrimaryKeySelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int updateByPrimaryKey(UserPO record);
}