package com.wwn.film.user.dao;

import com.wwn.film.user.entity.UserDO;
import org.springframework.stereotype.Repository;

@Repository
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int insert(UserDO record);

    UserDO selectByUsername(String username);

    Integer validateRecord(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    UserDO selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_user_t
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    int updateByPrimaryKey(UserDO record);
}