package com.wwn.film.film.dao;

import com.wwn.film.film.entity.ActorPO;
import org.springframework.stereotype.Repository;

@Repository
public interface ActorPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_actor_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_actor_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insert(ActorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_actor_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insertSelective(ActorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_actor_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    ActorPO selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_actor_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKeySelective(ActorPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_actor_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKey(ActorPO record);
}