package com.wwn.film.film.dao;

import com.wwn.film.film.entity.AreaPO;
import org.springframework.stereotype.Repository;

@Repository
public interface AreaPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_area_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_area_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insert(AreaPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_area_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insertSelective(AreaPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_area_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    AreaPO selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_area_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKeySelective(AreaPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_area_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKey(AreaPO record);
}