package com.wwn.film.film.dao;

import com.wwn.film.film.entity.CategoryPO;
import org.springframework.stereotype.Repository;

@Repository
public interface CategoryPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_cat_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_cat_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insert(CategoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_cat_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insertSelective(CategoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_cat_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    CategoryPO selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_cat_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKeySelective(CategoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_cat_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKey(CategoryPO record);
}