package com.wwn.film.film.dao;

import com.wwn.film.film.entity.FilmInfoPO;
import com.wwn.film.film.entity.FilmInfoPOWithBLOBs;
import org.springframework.stereotype.Repository;

@Repository
public interface FilmInfoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_film_info_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_film_info_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insert(FilmInfoPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_film_info_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insertSelective(FilmInfoPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_film_info_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    FilmInfoPOWithBLOBs selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_film_info_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKeySelective(FilmInfoPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_film_info_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(FilmInfoPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_film_info_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKey(FilmInfoPO record);
}