package com.wwn.film.film.dao;

import com.wwn.film.film.entity.YearPO;
import org.springframework.stereotype.Repository;

@Repository
public interface YearPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_year_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int deleteByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_year_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insert(YearPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_year_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int insertSelective(YearPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_year_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    YearPO selectByPrimaryKey(Integer uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_year_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKeySelective(YearPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mooc_year_dict_t
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    int updateByPrimaryKey(YearPO record);
}