package com.wwn.film.film.entity;

public class ActorPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_actor_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_actor_t.actor_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String actorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_actor_t.actor_img
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String actorImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_actor_t.UUID
     *
     * @return the value of mooc_actor_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_actor_t.UUID
     *
     * @param uuid the value for mooc_actor_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_actor_t.actor_name
     *
     * @return the value of mooc_actor_t.actor_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getActorName() {
        return actorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_actor_t.actor_name
     *
     * @param actorName the value for mooc_actor_t.actor_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setActorName(String actorName) {
        this.actorName = actorName == null ? null : actorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_actor_t.actor_img
     *
     * @return the value of mooc_actor_t.actor_img
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getActorImg() {
        return actorImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_actor_t.actor_img
     *
     * @param actorImg the value for mooc_actor_t.actor_img
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setActorImg(String actorImg) {
        this.actorImg = actorImg == null ? null : actorImg.trim();
    }
}