package com.wwn.film.film.entity;

public class BannerPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_banner_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_banner_t.banner_address
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String bannerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_banner_t.banner_url
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String bannerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_banner_t.is_valid
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_banner_t.UUID
     *
     * @return the value of mooc_banner_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_banner_t.UUID
     *
     * @param uuid the value for mooc_banner_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_banner_t.banner_address
     *
     * @return the value of mooc_banner_t.banner_address
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getBannerAddress() {
        return bannerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_banner_t.banner_address
     *
     * @param bannerAddress the value for mooc_banner_t.banner_address
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setBannerAddress(String bannerAddress) {
        this.bannerAddress = bannerAddress == null ? null : bannerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_banner_t.banner_url
     *
     * @return the value of mooc_banner_t.banner_url
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_banner_t.banner_url
     *
     * @param bannerUrl the value for mooc_banner_t.banner_url
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl == null ? null : bannerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_banner_t.is_valid
     *
     * @return the value of mooc_banner_t.is_valid
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_banner_t.is_valid
     *
     * @param isValid the value for mooc_banner_t.is_valid
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}