package com.wwn.film.film.entity;

public class CategoryPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_cat_dict_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_cat_dict_t.show_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String showName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_cat_dict_t.UUID
     *
     * @return the value of mooc_cat_dict_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_cat_dict_t.UUID
     *
     * @param uuid the value for mooc_cat_dict_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_cat_dict_t.show_name
     *
     * @return the value of mooc_cat_dict_t.show_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_cat_dict_t.show_name
     *
     * @param showName the value for mooc_cat_dict_t.show_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setShowName(String showName) {
        this.showName = showName == null ? null : showName.trim();
    }
}