package com.wwn.film.film.entity;

public class FilmInfoPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.film_id
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String filmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.film_en_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String filmEnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.film_score
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String filmScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.film_score_num
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmScoreNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.film_length
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.director_id
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer directorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.UUID
     *
     * @return the value of mooc_film_info_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.UUID
     *
     * @param uuid the value for mooc_film_info_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.film_id
     *
     * @return the value of mooc_film_info_t.film_id
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getFilmId() {
        return filmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.film_id
     *
     * @param filmId the value for mooc_film_info_t.film_id
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmId(String filmId) {
        this.filmId = filmId == null ? null : filmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.film_en_name
     *
     * @return the value of mooc_film_info_t.film_en_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getFilmEnName() {
        return filmEnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.film_en_name
     *
     * @param filmEnName the value for mooc_film_info_t.film_en_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmEnName(String filmEnName) {
        this.filmEnName = filmEnName == null ? null : filmEnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.film_score
     *
     * @return the value of mooc_film_info_t.film_score
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getFilmScore() {
        return filmScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.film_score
     *
     * @param filmScore the value for mooc_film_info_t.film_score
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmScore(String filmScore) {
        this.filmScore = filmScore == null ? null : filmScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.film_score_num
     *
     * @return the value of mooc_film_info_t.film_score_num
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmScoreNum() {
        return filmScoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.film_score_num
     *
     * @param filmScoreNum the value for mooc_film_info_t.film_score_num
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmScoreNum(Integer filmScoreNum) {
        this.filmScoreNum = filmScoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.film_length
     *
     * @return the value of mooc_film_info_t.film_length
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmLength() {
        return filmLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.film_length
     *
     * @param filmLength the value for mooc_film_info_t.film_length
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmLength(Integer filmLength) {
        this.filmLength = filmLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.director_id
     *
     * @return the value of mooc_film_info_t.director_id
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getDirectorId() {
        return directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.director_id
     *
     * @param directorId the value for mooc_film_info_t.director_id
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setDirectorId(Integer directorId) {
        this.directorId = directorId;
    }
}