package com.wwn.film.film.entity;

public class FilmInfoPOWithBLOBs extends FilmInfoPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.biography
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String biography;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_info_t.film_imgs
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String filmImgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.biography
     *
     * @return the value of mooc_film_info_t.biography
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getBiography() {
        return biography;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.biography
     *
     * @param biography the value for mooc_film_info_t.biography
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setBiography(String biography) {
        this.biography = biography == null ? null : biography.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_info_t.film_imgs
     *
     * @return the value of mooc_film_info_t.film_imgs
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getFilmImgs() {
        return filmImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_info_t.film_imgs
     *
     * @param filmImgs the value for mooc_film_info_t.film_imgs
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmImgs(String filmImgs) {
        this.filmImgs = filmImgs == null ? null : filmImgs.trim();
    }
}