package com.wwn.film.film.entity;

import java.util.Date;

public class FilmPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String filmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_type
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.img_address
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String imgAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_score
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String filmScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_preSaleNum
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmPresalenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_box_office
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmBoxOffice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_source
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_cats
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private String filmCats;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_area
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_date
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_time
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Date filmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_film_t.film_status
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    private Integer filmStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.UUID
     *
     * @return the value of mooc_film_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.UUID
     *
     * @param uuid the value for mooc_film_t.UUID
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_name
     *
     * @return the value of mooc_film_t.film_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getFilmName() {
        return filmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_name
     *
     * @param filmName the value for mooc_film_t.film_name
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmName(String filmName) {
        this.filmName = filmName == null ? null : filmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_type
     *
     * @return the value of mooc_film_t.film_type
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmType() {
        return filmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_type
     *
     * @param filmType the value for mooc_film_t.film_type
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmType(Integer filmType) {
        this.filmType = filmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.img_address
     *
     * @return the value of mooc_film_t.img_address
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getImgAddress() {
        return imgAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.img_address
     *
     * @param imgAddress the value for mooc_film_t.img_address
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setImgAddress(String imgAddress) {
        this.imgAddress = imgAddress == null ? null : imgAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_score
     *
     * @return the value of mooc_film_t.film_score
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getFilmScore() {
        return filmScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_score
     *
     * @param filmScore the value for mooc_film_t.film_score
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmScore(String filmScore) {
        this.filmScore = filmScore == null ? null : filmScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_preSaleNum
     *
     * @return the value of mooc_film_t.film_preSaleNum
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmPresalenum() {
        return filmPresalenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_preSaleNum
     *
     * @param filmPresalenum the value for mooc_film_t.film_preSaleNum
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmPresalenum(Integer filmPresalenum) {
        this.filmPresalenum = filmPresalenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_box_office
     *
     * @return the value of mooc_film_t.film_box_office
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmBoxOffice() {
        return filmBoxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_box_office
     *
     * @param filmBoxOffice the value for mooc_film_t.film_box_office
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmBoxOffice(Integer filmBoxOffice) {
        this.filmBoxOffice = filmBoxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_source
     *
     * @return the value of mooc_film_t.film_source
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmSource() {
        return filmSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_source
     *
     * @param filmSource the value for mooc_film_t.film_source
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmSource(Integer filmSource) {
        this.filmSource = filmSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_cats
     *
     * @return the value of mooc_film_t.film_cats
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public String getFilmCats() {
        return filmCats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_cats
     *
     * @param filmCats the value for mooc_film_t.film_cats
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmCats(String filmCats) {
        this.filmCats = filmCats == null ? null : filmCats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_area
     *
     * @return the value of mooc_film_t.film_area
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmArea() {
        return filmArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_area
     *
     * @param filmArea the value for mooc_film_t.film_area
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmArea(Integer filmArea) {
        this.filmArea = filmArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_date
     *
     * @return the value of mooc_film_t.film_date
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmDate() {
        return filmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_date
     *
     * @param filmDate the value for mooc_film_t.film_date
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmDate(Integer filmDate) {
        this.filmDate = filmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_time
     *
     * @return the value of mooc_film_t.film_time
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Date getFilmTime() {
        return filmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_time
     *
     * @param filmTime the value for mooc_film_t.film_time
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmTime(Date filmTime) {
        this.filmTime = filmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_film_t.film_status
     *
     * @return the value of mooc_film_t.film_status
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public Integer getFilmStatus() {
        return filmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_film_t.film_status
     *
     * @param filmStatus the value for mooc_film_t.film_status
     *
     * @mbg.generated Thu Aug 06 14:38:21 CST 2020
     */
    public void setFilmStatus(Integer filmStatus) {
        this.filmStatus = filmStatus;
    }
}