package com.wwn.film.user.entity;

import java.util.Date;

public class UserPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.UUID
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.user_name
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.user_pwd
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.nick_name
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.user_sex
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private Integer userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.birthday
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.email
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.user_phone
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.address
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.head_url
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.biography
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private String biography;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.life_state
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private Integer lifeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.begin_time
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mooc_user_t.update_time
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.UUID
     *
     * @return the value of mooc_user_t.UUID
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.UUID
     *
     * @param uuid the value for mooc_user_t.UUID
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.user_name
     *
     * @return the value of mooc_user_t.user_name
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.user_name
     *
     * @param userName the value for mooc_user_t.user_name
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.user_pwd
     *
     * @return the value of mooc_user_t.user_pwd
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.user_pwd
     *
     * @param userPwd the value for mooc_user_t.user_pwd
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.nick_name
     *
     * @return the value of mooc_user_t.nick_name
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.nick_name
     *
     * @param nickName the value for mooc_user_t.nick_name
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.user_sex
     *
     * @return the value of mooc_user_t.user_sex
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.user_sex
     *
     * @param userSex the value for mooc_user_t.user_sex
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.birthday
     *
     * @return the value of mooc_user_t.birthday
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.birthday
     *
     * @param birthday the value for mooc_user_t.birthday
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.email
     *
     * @return the value of mooc_user_t.email
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.email
     *
     * @param email the value for mooc_user_t.email
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.user_phone
     *
     * @return the value of mooc_user_t.user_phone
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.user_phone
     *
     * @param userPhone the value for mooc_user_t.user_phone
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.address
     *
     * @return the value of mooc_user_t.address
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.address
     *
     * @param address the value for mooc_user_t.address
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.head_url
     *
     * @return the value of mooc_user_t.head_url
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.head_url
     *
     * @param headUrl the value for mooc_user_t.head_url
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.biography
     *
     * @return the value of mooc_user_t.biography
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public String getBiography() {
        return biography;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.biography
     *
     * @param biography the value for mooc_user_t.biography
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setBiography(String biography) {
        this.biography = biography == null ? null : biography.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.life_state
     *
     * @return the value of mooc_user_t.life_state
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public Integer getLifeState() {
        return lifeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.life_state
     *
     * @param lifeState the value for mooc_user_t.life_state
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setLifeState(Integer lifeState) {
        this.lifeState = lifeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.begin_time
     *
     * @return the value of mooc_user_t.begin_time
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.begin_time
     *
     * @param beginTime the value for mooc_user_t.begin_time
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mooc_user_t.update_time
     *
     * @return the value of mooc_user_t.update_time
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mooc_user_t.update_time
     *
     * @param updateTime the value for mooc_user_t.update_time
     *
     * @mbg.generated Thu Jul 16 11:24:50 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}